add reset button
CoolDotty/fvf-decks pull request #14
Opened 2023-10-29 07:31 UTC by devkennyy

- added a reset button that removes all equipped cards from deck

2023-10-30 21:31 UTC, KarlTheCool requested changes
Couple comments. Take a look!

2023-10-30 21:31 UTC, x3cca commented on src/Modal/styles.css
> +  margin: 0;
```suggestion
  margin: 0;
  margin-bottom: 0.5rem;
  text-align: center;
```

Extra margin because the heading spacing being the same as the options looks a little funny.
Text align center so it looks centered if there's ever a line break.

2023-10-30 21:31 UTC, x3cca commented on src/Modal/styles.css
> +  max-width: 450px;
```suggestion
  max-width: 30rem;
```
Prefer using rem / em values to save time later when mobile mode gets fixed lol

2023-10-30 21:31 UTC, x3cca commented on src/Modal/index.jsx
> +      <Button onClick={onConfirm} label="CONFIRM" />
```suggestion
      <h2>Clear Deck?</h2>
      <Button onClick={onConfirm} label="Yes" />
```

A little bit of clarification on what the action is doing.
Pose it as a question.

2023-10-30 21:31 UTC, KarlTheCool commented on src/App.jsx
> +              onConfirm={() => { setMyDeck([]); setIsResetModalOpen(false); }}
```suggestion
              onConfirm={() => {
                setMyDeck([]);
                setIsResetModalOpen(false);
              }}
```
No need for this to be a one liner.

2023-10-30 21:31 UTC, KarlTheCool commented on src/Modal/styles.css
> +  left: 50%;
```suggestion
  left: -50%;
```

Super cool bounce animation that looks like in-game part 1 😎

2023-10-30 21:31 UTC, KarlTheCool commented on src/Modal/styles.css
> +}
```suggestion
  gap: 0.8em;

  transition:
    /* EaseInBack https://www.cssportal.com/css-cubic-bezier-generator/ */
    top cubic-bezier(0.6, -0.28, 0.735, 0.045) 0.33s 0s,
    visibility linear 0.0s 0.33s;
}

.modal.open {
  visibility: visible;
  top: 50%;
  transition:
    /* EaseOutIn https://www.cssportal.com/css-cubic-bezier-generator/ */
    top cubic-bezier( 0.175, 0.885, 0.32, 1.275 ) 0.33s 0s,
    visibility linear 0s 0s;
}
```


Super cool bounce animation that looks like in-game part 2 😎

2023-10-30 21:31 UTC, KarlTheCool commented on src/Modal/styles.css
> +}
```suggestion
}

```

End files with newline

2023-10-30 23:12 UTC, KarlTheCool requested changes

2023-10-30 23:12 UTC, KarlTheCool commented on src/Modal/styles.css
> +  left: -50%;
```suggestion
  top: -50%;
  left: 50%;
```

top should be -50% instead of left :p

2023-10-31 00:09 UTC, KarlTheCool approved these changes
Should be good now! Thanks!

2023-10-31 00:09 UTC, merged